### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by michaelbub** [smartgrids-aau/punyinformde#1]
ext_menu.h

- `print "q: Vorheriges Menu^";` Shoud be Menü (it's correct in other places)
- ` print "^Wähle 1 zu ", lines, ...` Should be "Wähle 1 bis"
- `Constant PKEY__TX       = "P = vorherig";` Should be "vorheriges" (if this is referring to "Thema")
- `print "^[Bitte drücke SPACE.]";` There is a name for SPACE in German, Leertaste. So "Bitte drücke die Leertaste."

ext_talk_menu.h

- English version has `Verb 'talk' 'converse' 'interview' 'interrogate'`. "interrogate" is missing in the German version, probably should be "verhöre".

ext_waittime.h

- I think it doesn't matter, but it says ` 'Runde'/'Runden'` while everything else is lowercase
- Things after` #Ifdef STATUSLINE_SCORE;` are not translated at all

parser.h

-` print "Meinst du ";` is not wrong, but I'd prefer "Meintest du". A matter of taste.
- `if(p_parse_pointer --> 0 == 'es' or 'ihn' or 'sie' or 'sie') {` Unless this is to remind oneself that there are two versions of "sie", the "sie" appears twice.
- Likewise the following switch has 'sie' twice. This is harder to solve, as the parser currently can not distuingish between the two 'sie' cases (AKA her and them in English).
- `print "(nimmt ";` Usually I get the feeling that parser messages are like the parser itself talking loudly and talking about itself, so I think it should be "(nehme foobar an)".

puny.h

- `name 'ich' 'selbst',` I am not that familar with the selfobj, but I think it should include 'mich', for stuff like "schau mich an"  (or however you would phrase it now in German).

I have yet to look at the very text-heavy files. So more to come.

**Comment by unfailx** [comment]
Thank you! I fixed all of the issues.
